//SIGN UP
export const GET_AREA_CODES_LIST_DATA = 'GET_AREA_CODES_LIST_DATA';
export const SET_SIGN_UP_AREA_CODES_LIST_DATA = 'SET_SIGN_UP_AREA_CODES_LIST_DATA';
export const CHECK_AREA_CODE = 'CHECK_AREA_CODE';
export const SET_SELECTED_AREA_CODE = 'SET_SELECTED_AREA_CODE';
export const CHECK_PHONE_NUMBER = 'CHECK_PHONE_NUMBER';

export const GET_PHONE_NUMBERS_LIST_DATA = 'GET_PHONE_NUMBERS_LIST_DATA';
export const SET_SIGN_UP_PHONE_NUMBERS_LIST_DATA = 'SET_SIGN_UP_PHONE_NUMBERS_LIST_DATA';
export const SET_PENDING_TYPE = 'SET_PENDING_TYPE';

export const SEND_VERIFICATION_SMS = 'SEND_VERIFICATION_SMS';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CHECK_SMS_TOKEN = 'CHECK_SMS_TOKEN';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const ORDER_PHONE_NUMBERS = 'ORDER_PHONE_NUMBERS';

//ACTIONS
export const SAVE_LAST_ACTION = 'SAVE_LAST_ACTION';
export const SET_LAST_CALL_COUNT = 'SET_LAST_CALL_COUNT';
export const SET_SCROLL_REF = 'SET_SCROLL_REF';

//USER
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_USER_INITIAL_STATE = 'SET_USER_INITIAL_STATE';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_ACTIVE_PRODUCTS = 'SET_ACTIVE_PRODUCTS';
export const REFRESH_SIGNALR_TOKEN = 'REFRESH_SIGNALR_TOKEN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const ADD_FILE = 'ADD_FILE';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const SET_UNREAD_MESSAGES_COUNT = 'SET_UNREAD_MESSAGES_COUNT';
export const SET_UNREAD_HISTORY_COUNT = 'SET_UNREAD_HISTORY_COUNT';
export const SET_UNREAD_VOICEMAIL_COUNT = 'SET_UNREAD_VOICEMAIL_COUNT';
export const GET_BROADSOFT_STATUSES = 'GET_BROADSOFT_STATUSES';
export const CHANGE_BROADSOFT_STATUSES = 'CHANGE_BROADSOFT_STATUSES';
export const SET_IN_APP_NOTIFICATION_DATA = 'SET_IN_APP_NOTIFICATION_DATA';
export const GET_BADGES = 'GET_BADGES';
export const ADD_VOICEMAIL_GREETING = 'ADD_VOICEMAIL_GREETING';
export const GET_VOICEMAIL_GREETINGS = 'GET_VOICEMAIL_GREETINGS';
export const SET_VOICEMAIL_GREATINGS = 'SET_VOICEMAIL_GREATINGS';
export const ENABLE_VOICEMAIL_GREETING = 'ENABLE_VOICEMAIL_GREETING';
export const DELETE_VOICEMAIL_GREETING = 'DELETE_VOICEMAIL_GREETING';
export const UPDATE_VOICEMAIL_GREETING = 'UPDATE_VOICEMAIL_GREETING';
export const GET_AUDIO_FILE_BY_NAME = 'GET_AUDIO_FILE_BY_NAME';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const CHANGE_REGISTERED_NUMBER = 'CHANGE_REGISTERED_NUMBER';
export const CHECK_SMS_TOKEN_CHANGE_NUMBER = 'CHECK_SMS_TOKEN_CHANGE_NUMBER';
export const SET_HISTORY_DATA_LOAD_SCREEN = 'SET_HISTORY_DATA_LOAD_SCREEN';
export const SET_FCM_TOKEN = 'SET_FCM_TOKEN';

//VOICEMAILS
export const SET_VOICEMAILS = 'SET_VOICEMAILS';
export const ADD_VOICEMAIL = 'ADD_VOICEMAIL';
export const GET_VOICEMAILS = 'GET_VOICEMAILS';
export const GET_VOICEMAIL_BY_ID = 'GET_VOICEMAIL_BY_ID';
export const MARK_VOICEMAIL = 'MARK_VOICEMAIL';
export const MARK_VOICEMAIL_READED = 'MARK_VOICEMAIL_READED';
export const SET_VOICEMAIL_CONTENT = 'SET_VOICEMAIL_CONTENT';
export const DELETE_VOICEMAIL = 'DELETE_VOICEMAIL';
export const DELETE_VOICEMAIL_IN_LIST = 'DELETE_VOICEMAIL_IN_LIST';

//CALL
export const GET_CALL_HISTORY = 'GET_CALL_HISTORY';
export const SET_CALL_HISTORY = 'SET_CALL_HISTORY';
export const ADD_CALL = 'ADD_CALL';
export const GENERATE_OUTGOING_CALL_NUMBER = 'GENERATE_OUTGOING_CALL_NUMBER';
export const SET_SEEN_CALLS_REQ = 'SET_SEEN_CALLS_REQ';

//CONTACT
export const CREATE_CONTACT = 'CREATE_CONTACT';
export const GET_CONTACTS = 'GET_CONTACTS';
export const GET_SUGGESTIONS_CONTACTS = 'GET_SUGGESTIONS_CONTACTS';
export const SET_APP_CONTACTS = 'SET_APP_CONTACTS';
export const GET_CONTACT_BY_ID = 'GET_CONTACT_BY_ID';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const GET_BLOCKED_CONTACTS = 'GET_BLOCKED_CONTACTS';
export const SET_BLOCKED_CONTACTS = 'SET_BLOCKED_CONTACTS';
export const SET_BLOCKED_NUMBERS = 'SET_BLOCKED_NUMBERS';
export const BLOCK_NUMBER = 'BLOCK_NUMBER';
export const UNBLOCK_NUMBER = 'UNBLOCK_NUMBER';
export const SET_CONTACTS_SYNCING = 'SET_CONTACTS_SYNCING';

//CHAT
export const GET_PRIVATE_CHAT = 'GET_PRIVATE_CHAT';
export const SEND_PRIVATE_MESSAGE = 'SEND_PRIVATE_MESSAGE';
export const GET_CHATS = 'GET_CHATS';
export const SET_CHATS = 'SET_CHATS';
export const DELETE_CHAT_HISTORY = 'DELETE_CHAT_HISTORY';
export const CHANGE_LAST_SEEN_TIME = 'CHANGE_LAST_SEEN_TIME';
export const SET_ACTIVE_CHAT_ID = 'SET_ACTIVE_CHAT_ID';
export const SET_ACTIVE_CHAT_LIST_DATA = 'SET_ACTIVE_CHAT_LIST_DATA';
export const GET_MESSAGES = 'GET_MESSAGES';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const SET_SHOW_CHANNELS_LIST = 'SET_SHOW_CHANNELS_LIST';
export const REFRESH_CHANNELS_LIST = 'REFRESH_CHANNELS_LIST';
export const UPDATE_UNSEEN_CHATS_COUNT = 'UPDATE_UNSEEN_CHATS_COUNT';
